// Code generated by moq; DO NOT EDIT.
// github.com/matryer/moq

package search

import (
	"context"
	"github.com/o-ga09/gourmet-mcp/internal/jev"
	"github.com/o-ga09/gourmet-mcp/internal/places"
	"sync"
)

// Ensure, that PlaceSearcherMock does implement PlaceSearcher.
// If this is not the case, regenerate this file with moq.
var _ PlaceSearcher = &PlaceSearcherMock{}

// PlaceSearcherMock is a mock implementation of PlaceSearcher.
//
//	func TestSomethingThatUsesPlaceSearcher(t *testing.T) {
//
//		// make and configure a mocked PlaceSearcher
//		mockedPlaceSearcher := &PlaceSearcherMock{
//			SearchTextFunc: func(ctx context.Context, r places.SearchTextRequest) ([]places.Place, error) {
//				panic("mock out the SearchText method")
//			},
//		}
//
//		// use mockedPlaceSearcher in code that requires PlaceSearcher
//		// and then make assertions.
//
//	}
type PlaceSearcherMock struct {
	// SearchTextFunc mocks the SearchText method.
	SearchTextFunc func(ctx context.Context, r places.SearchTextRequest) ([]places.Place, error)

	// calls tracks calls to the methods.
	calls struct {
		// SearchText holds details about calls to the SearchText method.
		SearchText []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// R is the r argument value.
			R places.SearchTextRequest
		}
	}
	lockSearchText sync.RWMutex
}

// SearchText calls SearchTextFunc.
func (mock *PlaceSearcherMock) SearchText(ctx context.Context, r places.SearchTextRequest) ([]places.Place, error) {
	if mock.SearchTextFunc == nil {
		panic("PlaceSearcherMock.SearchTextFunc: method is nil but PlaceSearcher.SearchText was just called")
	}
	callInfo := struct {
		Ctx context.Context
		R   places.SearchTextRequest
	}{
		Ctx: ctx,
		R:   r,
	}
	mock.lockSearchText.Lock()
	mock.calls.SearchText = append(mock.calls.SearchText, callInfo)
	mock.lockSearchText.Unlock()
	return mock.SearchTextFunc(ctx, r)
}

// SearchTextCalls gets all the calls that were made to SearchText.
// Check the length with:
//
//	len(mockedPlaceSearcher.SearchTextCalls())
func (mock *PlaceSearcherMock) SearchTextCalls() []struct {
	Ctx context.Context
	R   places.SearchTextRequest
} {
	var calls []struct {
		Ctx context.Context
		R   places.SearchTextRequest
	}
	mock.lockSearchText.RLock()
	calls = mock.calls.SearchText
	mock.lockSearchText.RUnlock()
	return calls
}

// Ensure, that JudgeMock does implement Judge.
// If this is not the case, regenerate this file with moq.
var _ Judge = &JudgeMock{}

// JudgeMock is a mock implementation of Judge.
//
//	func TestSomethingThatUsesJudge(t *testing.T) {
//
//		// make and configure a mocked Judge
//		mockedJudge := &JudgeMock{
//			NoulFunc: func(ctx context.Context, state any, q jev.NoulQuestion) (float64, error) {
//				panic("mock out the Noul method")
//			},
//		}
//
//		// use mockedJudge in code that requires Judge
//		// and then make assertions.
//
//	}
type JudgeMock struct {
	// NoulFunc mocks the Noul method.
	NoulFunc func(ctx context.Context, state any, q jev.NoulQuestion) (float64, error)

	// calls tracks calls to the methods.
	calls struct {
		// Noul holds details about calls to the Noul method.
		Noul []struct {
			// Ctx is the ctx argument value.
			Ctx context.Context
			// State is the state argument value.
			State any
			// Q is the q argument value.
			Q jev.NoulQuestion
		}
	}
	lockNoul sync.RWMutex
}

// Noul calls NoulFunc.
func (mock *JudgeMock) Noul(ctx context.Context, state any, q jev.NoulQuestion) (float64, error) {
	if mock.NoulFunc == nil {
		panic("JudgeMock.NoulFunc: method is nil but Judge.Noul was just called")
	}
	callInfo := struct {
		Ctx   context.Context
		State any
		Q     jev.NoulQuestion
	}{
		Ctx:   ctx,
		State: state,
		Q:     q,
	}
	mock.lockNoul.Lock()
	mock.calls.Noul = append(mock.calls.Noul, callInfo)
	mock.lockNoul.Unlock()
	return mock.NoulFunc(ctx, state, q)
}

// NoulCalls gets all the calls that were made to Noul.
// Check the length with:
//
//	len(mockedJudge.NoulCalls())
func (mock *JudgeMock) NoulCalls() []struct {
	Ctx   context.Context
	State any
	Q     jev.NoulQuestion
} {
	var calls []struct {
		Ctx   context.Context
		State any
		Q     jev.NoulQuestion
	}
	mock.lockNoul.RLock()
	calls = mock.calls.Noul
	mock.lockNoul.RUnlock()
	return calls
}
