name: lint and test
on:
  pull_request:
    branches:
      - "main"
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
  push:
    branches:
      - "main"
    paths:
      - '**.go'
      - 'go.mod'
      - 'go.sum'
jobs:
  lint:
    name: golangci-lint
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod
      - name: golangci-lint
        uses: golangci/golangci-lint-action@9fae48acfc02a90574d7c304a1758ef9895495fa # v7.0.1
        with:
          version: v2.12.1
          args: "--timeout=5m --config=./.golangci.yaml ./..."

  test:
    name: test
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@11d5960a326750d5838078e36cf38b85af677262 # v4.4.0
      - uses: actions/setup-go@40f1582b2485089dde7abd97c1529aa768e1baff # v5.6.0
        with:
          go-version-file: go.mod
      - name: testing
        run: go test -race ./...
